#ifndef COMMON_H
#define COMMON_H

typedef enum {
    TOKEN_NUMBER, TOKEN_STRING, TOKEN_IDENTIFIER,
    TOKEN_PRINT, TOKEN_REVERSE, TOKEN_GOTO, TOKEN_LIST, TOKEN_RUN, 
    TOKEN_SYSTEM, TOKEN_QUIT, TOKEN_LET, TOKEN_NEW, TOKEN_EQUALS,
    TOKEN_PSET, TOKEN_LINE, TOKEN_CIRCLE, TOKEN_PAINT, TOKEN_SCREEN, TOKEN_LOCATE, TOKEN_COLOR,
    TOKEN_IF, TOKEN_THEN, TOKEN_ELSE, TOKEN_END, TOKEN_REM, TOKEN_GOSUB, TOKEN_RETURN, TOKEN_DIM, TOKEN_DEF,
    TOKEN_FOR, TOKEN_TO, TOKEN_NEXT, TOKEN_STEP, TOKEN_CLS, TOKEN_SLEEP,
    TOKEN_OPEN, TOKEN_CLOSE, TOKEN_AS, TOKEN_NAME, TOKEN_INPUT, TOKEN_SEEK, TOKEN_DELETE, TOKEN_DATA, TOKEN_READ, TOKEN_RESTORE, TOKEN_RANDOMIZE, TOKEN_KILL, TOKEN_FILES, TOKEN_CHDIR, TOKEN_MKDIR, TOKEN_RMDIR, TOKEN_SHELL, TOKEN_ERASE, TOKEN_LINE_INPUT, TOKEN_EOF_FUNC,
    TOKEN_DRAW, TOKEN_OPTION, TOKEN_BASE,
    TOKEN_USING, TOKEN_APOSTROPHE,
    TOKEN_PUT, TOKEN_GET, TOKEN_GETS,
    TOKEN_WHILE, TOKEN_WEND, TOKEN_KEY, TOKEN_INKEY, TOKEN_TIMER,
    TOKEN_BEEP,
    TOKEN_PLAY, TOKEN_SOUND,
    TOKEN_PEEK, TOKEN_POKE, TOKEN_VARPTR,
    TOKEN_LEFT, TOKEN_RIGHT, TOKEN_MID,
    TOKEN_SPACE, TOKEN_SPC, TOKEN_STRING_FUNC,
    TOKEN_SWAP, TOKEN_ON, TOKEN_ERR,
    TOKEN_TIME, TOKEN_DATE,
    TOKEN_INSTR, TOKEN_STR, TOKEN_VAL, TOKEN_RESUME, TOKEN_ENVIRON,
    TOKEN_ASC, TOKEN_CHR, TOKEN_TAB, TOKEN_LEN,
    TOKEN_UCASE, TOKEN_LCASE, TOKEN_TRIM, TOKEN_LTRIM, TOKEN_RTRIM, TOKEN_HEX, TOKEN_OCT,
    TOKEN_EOF, TOKEN_ERROR, TOKEN_COMMA, TOKEN_SEMICOLON, TOKEN_COLON, TOKEN_LESS, TOKEN_GREATER,
    TOKEN_PLUS, TOKEN_MINUS, TOKEN_STAR, TOKEN_SLASH, TOKEN_LPAREN, TOKEN_RPAREN, 
    TOKEN_POWER, TOKEN_MOD, TOKEN_IDIV, TOKEN_HASH,
    TOKEN_ABS, TOKEN_SQR, TOKEN_SIN, TOKEN_COS, TOKEN_TAN, TOKEN_ATN, 
    TOKEN_EXP, TOKEN_LOG, TOKEN_INT, TOKEN_FIX, TOKEN_RND, TOKEN_SGN
} TokenType;

typedef struct {
    TokenType type;
    char text[256];
    int int_val;
    double double_val;
} Token;

typedef struct Statement {
    int line_number;
    char raw_command[256];
    struct Statement *next;
} Statement;

// Simple variable storage
typedef struct {
    char name[32];
    double value;
    char *s_value;
    double *array;
    char **s_array;
    int array_size;
    int num_dims;
    int dims[3];  // Support up to 3D arrays
} Variable;

#endif
